# Generated by Django 2.2.6 on 2020-08-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='address',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone_no',
            field=models.IntegerField(default=0),
        ),
    ]
