# Generated by Django 2.2.6 on 2020-08-17 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_companyregistertable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('job_details', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('salry', models.FloatField(default=0)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.CompanyRegisterTable')),
            ],
        ),
    ]
