# Generated by Django 2.2.6 on 2020-08-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_applied_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='applied_jobs',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
