# Generated by Django 2.2.6 on 2020-08-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_applied_jobs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_no',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
