# Generated by Django 2.2.6 on 2020-08-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200826_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='expert_status',
            field=models.BooleanField(default=False),
        ),
    ]
